# Generated by Django 4.2 on 2023-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar1.jpeg', null=True, upload_to='avatars/%Y/%M/%D/'),
        ),
    ]
